spring.application.name=Backend
spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/sistemaerp?serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=root
